### PR TITLE
Feature/hh naming fixes

### LINKED ISSUE #1727: Blanking out a household account naming field doesn't recalculate name
e.g. [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/HH_HouseholdNaming.cls#L342) it only calculates if it's nulled AND auto naming is enabled.

### PR DESCRIPTION
**Pull request by davidhabib**
# Critical Changes

# Changes

# Issues Closed
Fixes #1727

### CODE REVIEW

**Comment by davidhabib** [comment]
@njjc 1 fix ready for you.  thx.

File: src/aura/HH_Container/HH_ContainerHelper.js [hunk 1]
```diff
@@ -271,11 +271,11 @@
     updateNamingExclusions: function(component, hh) {
         var strExclusions = '';
         if (!component.get('v.isAutoName'))
-            strExclusions += 'Household__c.Name;';
```
Comment (njjc) [inline src/aura/HH_Container/HH_ContainerHelper.js]: Why this change? Haven't we always been using these weird strings? While I prefer to remove the Household__c portion, I'm worried about the possible side effects of changing this without a good mitigation strategy.

Comment (davidhabib) [inline src/aura/HH_Container/HH_ContainerHelper.js]: turns out the picklist values don't include Household__c.  the just had the field names.  The managehouseholdui code (from ryan) was setting household__c as well, but it didn't matter, because the code that looks at this field, was just doing a contains(fieldname).

So I fixed up the new managehouseholdui code to set the correct picklist values.

**Comment by davidhabib** [comment]
now also includes the Level test assertion fix when contact's are modified by workflow rules during insert.

File: src/aura/HH_Container/HH_ContainerHelper.js (hunk 1 above)
Comment (davidhabib) [inline src/aura/HH_Container/HH_ContainerHelper.js]: nope.  the code detects them by using contains(fieldname)
